spring.application.name=ASD_Flowers

spring.datasource.url=jdbc:postgresql://asdflowers:YR6aVMIauyoOS68IwqnC9kAYQRfnCsfT@dpg-d6l6dmk50q8c73bncrig-a/asdflowers
spring.datasource.username=asdflowers
spring.datasource.password=YR6aVMIauyoOS68IwqnC9kAYQRfnCsfT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}
