spring.application.name=ASD_Flowers

spring.datasource.url=jdbc:postgresql://dpg-d6m9a2f5gffc73ba0ma0-a.oregon-postgres.render.com:5432/asdflowers_71wj
spring.datasource.username=asdflowers
spring.datasource.password=H675aNuG4DPIh6ZAZRTGbRC8N7Yk0ewr
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
