spring.application.name=ASD_Flowers

spring.datasource.url=jdbc:postgresql://dpg-d7ackqp5pdvs73dcp9cg-a:5432/asdflowerdb?sslmode=require
spring.datasource.username=asdflowerdb_user
spring.datasource.password=rttixgDySat4gW5MwZSpklE0YfQqHuL0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
